repos:
  - repo: https://github.com/treeverse/dvc
    rev: 3.56.0
    hooks:
    - id: dvc-post-checkout
      stages:
        - post-checkout
      always_run: true
    - id: dvc-pre-commit
      stages:
        - pre-commit
    # - id: dvc-pre-push  # TODO add when switching away from local storage
    #   stages:
    #     - pre-push
